# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      OrganizationAccountAccessRole: ${{ secrets.ORG_ACCOUNTS }}
      TopicArn: ${{ secrets.SNS_TOPIC_ARN }}
      AuthorizedAccounts: ${{ secrets.SNS_TOPIC_ARN }}
      AutoDelete: off
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10.4"
      # setup boto3
      - name: install boto3
        run: pip install boto3
      # setup python-lambda-local
      - name: install python-lambda-local
        run: pip install python-lambda-local
      # Runs AWS Cross-Account Checker
      - name: Run checker
        run: python-lambda-local -f lambda_handler checker/main.py .github/event.json
